config:
  checksum: false
  install_tree:
    root: /cvmfs/sw-nightlies.hsf.org/spackages5
    projections:
      all: ${PACKAGE}/${VERSION}/${target}-${os}-${COMPILERNAME}${COMPILERVER}-opt/${HASH:5}
      build_type=Debug: ${PACKAGE}/${VERSION}/${target}-${os}-${COMPILERNAME}${COMPILERVER}-dbg/${HASH:5}
